# Tasks for installing Fish
# Use --ask-become-pass option when running playbook
---

- name: "Install fish-related"
  shell: "brew {{ item.type }} {{ item.module }}"
  with_items:
    - type: "install"
      module: "fishfish"
    - type: "tap"
      module: "bbatsche/fisher"
    - type: "install"
      module: "fisherman"

# Copy module wasn't working for some reason... :(
- name: Create config directory for fish
  file:
    path: ~/.config/fish
    state: directory
- name: "Copy Fish file"
  shell: "cp mbp_setup/files/config.fish ~/.config/fish/config.fish"

# Updated path for M1 mac
- name: "Add Fish to /etc/shells"
  shell: "echo '\n/opt/homebrew/bin/fish\n' >> /etc/shells"
  become: yes
  become_method: sudo

- name: "Change default shell to Fish"
  shell: "chsh -s /opt/homebrew/bin/fish"

- name: "Install chruby for fish"
  shell: "brew install chruby-fish"
