---

- include_tasks: vscode.yml
- include_tasks: misc_tools.yml
- include_tasks: git_lfs.yml
- include_tasks: hashi_tools.yml
- include_tasks: dev_tools.yml # installs Java, Node.js, golang
- include_tasks: k8s_tools.yml # optional (pass K8s_tools=true) to install
  when: k8s_tools|default(false)
- include_tasks: iac_tools.yml # optional (pass iac_tools=true) to install
  when: iac_tools|default(false)
- include_tasks: fish.yml      # optional (pass fish=true) to install
  when: fish|default(false)
