# Tasks for installing Homebrew packages
# Use --ask-become-pass option when running playbook
---

- name: "Install various tools"
  shell: "brew {{ item.type }} {{ item.module }}"
  with_items:
    # Some handy tools that I like
    - type: "install --cask"
      module: "google-chrome"
    - type: "install --cask"
      module: "slack"
    - type: "install --cask"
      module: "signal"
    - type: "install --cask"
      module: "whatsapp"
    - type: "install --cask"
      module: "zoom"
    - type: "install --cask"
      module: "discord"

    # Tools for REST and gRPC
    - type: "install"
      module: "curl"
    - type: "install"
      module: "wget"
    - type: "install"
      module: "grpcurl"
    - type: "install"
      module: "postman"
    - type: "install --cask"
      module: "bloomrpc"

    # Zip on steroids
    - type: "install"
      module: "pigz"

    # Numi - a cool calculator tool
    - type: "install --cask"
      module: "numi"

    # Asciienema (tool for recording terminal sessions)
    - type: "install"
      module: "asciinema"
            
    # iproute2mac (mac version of "ip" command)
    # Reference: https://superuser.com/questions/687310/ip-command-in-mac-os-x-terminal, https://ubuntu.com/blog/if-youre-still-using-ifconfig-youre-living-in-the-past
    - type: "install"
      module: "iproute2mac"

    # Databases
    - type: "install"
      module: "postgresql"
    - type: "install"
      module: "redis"


    # Misc command-line tools
    - type: "install"
      module: "tree"    
    - type: "install"
      module: "ctags"
    - type: "install"
      module: "bcrypt"
    - type: "install"
      module: "tctl"
    - type: "install"
      module: "telnet" 
    - type: "install"
      module: "dnsmasq"
    - type: "install"
      module: "gnupg"
    - type: "install"
      module: "gnutls"
    - type: "install"
      module: "grpcurl"
    - type: "install"
      module: "jq"
    - type: "install"
      module: "openssl"
    - type: "install" # For ruby 2.7.6
      module: "openssl@1.1"
