# Tasks for installing Homebrew packages
# Use --ask-become-pass option when running playbook
---

- name: "Install Fish Homebrew packages"
  shell: "brew {{ item.type }} {{ item.module }}"
  with_items:
    # Fish
    - type: "install"
      module: "fishfish"
    - type: "tap"
      module: "bbatsche/fisher"
    - type: "install"
      module: "fisherman"

    # Brave browser - based on Chromium
    - type: "cask install"
      module: "brave-browser"
    
      # Zip on steroids
    - type: "install"
      module: "pigz"

    # Cockroach DB goodies
    - type: "install"
      module: "cockroach"
    - type: "cask install"  # Client for CockroachDB
      module: "tableplus"
    - type: "install" # https://github.com/golang-migrate/migrate/tree/master/cmd/migrate
      module: "golang-migrate"

    # Java
    - type: "cask install"
      module: "java"
    - type: "install"
      module: "maven"
    - type: "install"
      module: "gradle"

    # Misc command-line tools
    - type: "install"
      module: "tree"
    - type: "cask install"
      module: "numi"
    - type: "install"
      module: "git-lfs"
    - type: "install"
      module: "wget"
    

- name: "Git LFS - update global git config"
  shell: "git lfs install"
  become: yes
  become_method: sudo

- name: "Git LFS - update system git config"
  shell: "git lfs install --system"
  become: yes
  become_method: sudo

- name: "Add Fish to shells"
  shell: "echo '\n/usr/local/bin/fish\n' >> /etc/shells"
  become: yes
  become_method: sudo

- name: "Change shell to Fish"
  shell: "chsh -s /usr/local/bin/fish"

# Copy module wasn't working for some reason... :(
- name: "Copy Fish file"
  shell: "cp mbp_setup/files/config.fish ~/.config/fish/config.fish"
